<?php echo $this->getContent();
	  echo \Phalcon\Tag::stylesheetLink("css/estilosTable.css");
?>


	<div class="row">
		<div class="col s12 m6 offset-m3 grey-text text-darken-2 center">
			<h3>Historial de Registros</h3>
		</div>
	</div>


<div class="container" style="margin-top: 30px;">

	<div class="row">
	    <div class="col s12" style="margin-bottom: 30px;">
	      <ul class="tabs">
	        <li class="tab col s2 offset-s1"><a class="active" href="#test_1">Fecha</a></li>
	        <li class="tab col s2"><a href="#test_2">Nombre</a></li>
	        <li class="tab col s2"><a href="#test_3">R Válidos</a></li>
	        <li class="tab col s2"><a href="#test_4">Sin Registro</a></li>
	        <li class="tab col s2"><a href="#test_5">#Reg/Persona</a></li>
	      </ul>
	    </div>
	    <div id="test_1" class="col s12 m10 offset-m1">
	    	<table class="responsive-table centered" >
		        <thead>
		          <tr class="white-text  light-blue darken-4 center">

		              <th>MATRÍCULA</th>
		              <th>NOMBRE COMPLETO</th>
		              <th>FECHA / HORA</th>
		          </tr>
		        </thead>
		        <tbody >
		        	<?php 
		        		if(isset($Registro1)){
		        			foreach ($Registro1 as $registro) {
		        			?>
							<tr>
					            <td><?php echo $registro->Id_Persona;?></td>
					            <td><?php echo $registro->Nombre." ".$registro->Ap_Paterno." ".$registro->Ap_Materno;?></td>
					            <td><?php echo $registro->Fecha_Hora;?></td>
					        </tr>
		        			<?php
		        			}
		        		}
		        	?>
		        </tbody>
			</table>
	    </div>
	    <div id="test_2" class="col s12 m10 offset-m1">
	    	<table class="responsive-table centered" >
		        <thead>
		          <tr class="white-text  light-blue darken-4 center">

		              <th>MATRÍCULA</th>
		              <th>NOMBRE COMPLETO</th>
		              <th>FECHA / HORA</th>
		          </tr>
		        </thead>
		        <tbody >
		        	<?php 
		        		if(isset($Registro2)){
		        			foreach ($Registro2 as $registro) {
		        			?>
							<tr>
					            <td><?php echo $registro->Id_Persona;?></td>
					            <td><?php echo $registro->Nombre." ".$registro->Ap_Paterno." ".$registro->Ap_Materno;?></td>
					            <td><?php echo $registro->Fecha_Hora;?></td>
					        </tr>
		        			<?php
		        			}
		        		}
		        	?>
		        </tbody>
			</table>
	    </div>
	    <div id="test_3" class="col s12 m10 offset-m1">
	    	<table class="responsive-table centered" >
		        <thead>
		          <tr class="white-text  light-blue darken-4 center">

		              <th>MATRÍCULA</th>
		              <th>NOMBRE COMPLETO</th>
		              <th>FECHA / HORA</th>
		          </tr>
		        </thead>
		        <tbody >
		        	<?php 
		        		if(isset($Registro3)){
		        			foreach ($Registro3 as $registro) {
		        			?>
							<tr>
					            <td><?php echo $registro->Id_Persona;?></td>
					            <td><?php echo $registro->Nombre_Com;?></td>
					            <td><?php echo $registro->Fecha_Hora;?></td>
					        </tr>
		        			<?php
		        			}
		        		}
		        	?>
		        </tbody>
			</table>
	    </div>
	    <div id="test_4" class="col s12 m10 offset-m1">
	    	<table class="responsive-table centered" >
		        <thead>
		          <tr class="white-text  light-blue darken-4 center">

		              <th>MATRÍCULA</th>
		              <th>NOMBRE COMPLETO</th>
		              
		          </tr>
		        </thead>
		        <tbody >
		        	<?php 
		        		if(isset($Registro4)){
		        			foreach ($Registro4 as $registro) {
		        			?>
							<tr>
					            <td><?php echo $registro['Id_Persona'];?></td>
					            <td><?php echo $registro['Nombre']." ".$registro['Ap_Paterno']." ".$registro['Ap_Materno'];?></td>
					            
					        </tr>
		        			<?php
		        			}
		        		}
		        	?>
		        </tbody>
			</table>
	    </div>
	    <div id="test_5" class="col s12 m10 offset-m1">
			<table class="responsive-table centered" >
		        <thead>
		          <tr class="white-text  light-blue darken-4 center">
		          	  <th># DE REGISTROS</th>
		              <th>MATRÍCULA</th>
		              <th>NOMBRE COMPLETO</th>
		              
		          </tr>
		        </thead>
		        <tbody >
		        	<?php 
		        		if(isset($Registro5)){
		        			foreach ($Registro5 as $registro) {
		        			?>
							<tr>
					            <td><?php echo $registro->Num_Reg;?></td>
					            <td><?php echo $registro->Id_Persona;?></td>
					            <td><?php echo $registro->Nombre." ".$registro->Ap_Paterno." ".$registro->Ap_Materno;?></td>
					        </tr>
		        			<?php
		        			}
		        		}
		        	?>
		        </tbody>
			</table>
		</div>
	</div>
	
</div>

<script type="text/javascript">
	$(document).ready(function(){
    $('.tabs').tabs();
  });
</script>

	
