<?php echo $this->getContent(); 
	echo \Phalcon\Tag::stylesheetLink("css/estilosGestion.css");
?>

<!--Carrusel de Imágenes-->
<div class="slider">
	    <ul class="slides">
	      <li>
	        <img src="https://cdn.pixabay.com/photo/2016/08/15/10/17/survey-1594962_960_720.jpg"> <!-- link para imagen en el nav -->
	        	<div class="caption center-align">
		          <h2>CheckIng-BUAP</h2>
		          <h4 class="light grey-text text-lighten-4">La aplicación para el registro de votantes BUAP.</h4>
		        </div>
	      </li>
	      <li>
	        <img src="https://cdn.pixabay.com/photo/2017/07/31/11/46/laptop-2557586_960_720.jpg"> <!-- random image -->
	        <div class="caption left-align">
	          <h2>Informate Bien</h2>
	          <h4 class="light grey-text text-lighten-3">Investiga todas las propuestas de cada candidato, para poder decidir</h4>
	        </div>
	      </li>
	      <li>
	        <img src="https://cdn.pixabay.com/photo/2017/07/10/23/45/cubes-2492010_960_720.jpg"> <!-- random image -->
	        <div class="caption right-align">
	          <h2>Vota!</h2>
	          <h4 class="light grey-text text-lighten-3">Elije el candidato de tu preferencia</h4>
	        </div>
	      </li>
	      <li>
	        <img src="https://cdn.pixabay.com/photo/2016/01/19/17/53/writing-1149962_960_720.jpg"> <!-- random image -->
	        <div class="caption center-align">
	          <h2>Un cambio para el bien de todos!</h2>
	        </div>
	      </li>
	    </ul>
</div>

<!--Contenedor Principal-->
<div class="container">
		
	<div class="col s12 m12" >
		<h3 class="grey-text text-darken-2" align="center">
			Registro Manual de Votantes
		</h3>
	</div>


	<div class="row">
      <div class="col s12" id="form_1" align="center" style="margin-top: 20px;">
	    
    	<?php echo $this->tag->form("gestion/cambioRegistro");?>
  		<div class="col s12 m12">
  			<h5 class="blue-text text-darken-4"><?php echo (isset($Reg_Result))? $Reg_Result:""; ?></h5>
  		</div>
  		<div class="col s12 m12">
  			<p class="grey-text text-darken-1">
  				Ingrese la matrícula o el número de trabajador para realizar la búsqueda.
  			</p>
  		</div>
  		<br><br><br><br><br>
  		<div class="row">
  			<div class="col s12 m6 offset-m3 input-field">

      			<?php echo $this->tag->textField([
      											'Matricula',
      											'onkeypress' => 'return checar(event)',
      											'type'      =>  'text',
      											'class' => 'validate',
      											 'data-length'=>"9",
      											 'value' => (isset($Reg_Result))? "":$this->request->getPost('Matricula')
      											]);?>
      			<label for="Matricula">Matricula</label>

				
      		</div>
      		<div class="col s12 m6 offset-m3 input-field">

      			<?php echo $this->tag->textField([
      											'Id_Dentro',
      											'value'      =>  '',
      											'style'     => 'display:none'
      											]);?>
      		</div>
  		</div>
  		
  		<br>
  		<div class="row">

			    <!-- Modal Trigger -->
				  <button id="boton_ajax" name="buttonBuscar" data-target="modal1" class="col s6 offset-s3 m4 offset-m4 waves-effect waves-light btn modal-trigger blue darken-4">Buscar</button>
				  
				  <!-- Modal Structure -->
				  <div id="modal1" class="modal modal-fixed-footer">
				    <div class="modal-content">
				    	<div class="row">
				    		<div class="col s12 ">
				    			<h4 id="label_header" align="center">Resultado de consulta</h4>
			      				<div class="divider"></div>
				    		</div>
				    		
				    	</div>
				      
				      <!--Información del usuario: -->
				      <div class="row">
				      	<div class="col s12 m6 offset-m3">
				      		<img src="https://cdn3.iconfinder.com/data/icons/medcare/512/patient_info-512.png" style="height: 50px; width: 50px;">

				      	</div>
				      </div>
				      
				      <div class="row">
				      	<div class="col s12 m4">
				      		<img id="img_user_modal" src="https://www.stickpng.com/assets/images/585e4beacb11b227491c3399.png" style="max-height: 200px; max-width: 200px;">
				      	</div>


				      	<div class="col s12 m8 " style=" text-align: left;">
					      	<div class="row">
					      		<div class="col 12s m12" id="row_header_user">
					      			<h5 id="label_header_user" align="center">Información Personal</h5>
		      						<div class="divider"></div>
					      		</div>
					      		<div class="col s12 m3 offset-m2">
				      			<h5 id="label_mat">Matrícula: </h5>
					      		</div>
					      		<div class="col s12 m6">
					      			<h5 align="center" id="matricula_ajax">...</h5>
					      		</div>
					      	

					      	
					      		<div class="col s12 m3 offset-m2">
					      			<h5 id="label_nom">Nombre: </h5>
					      		</div>
					      		<div class="col s12 m6">
					      			<h5 align="center" id="nombre_ajax">...</h5>
					      		</div>
					      		
					      	</div>
					      		
					      	
					    </div>
				      </div>    	
					   
				    </div>


				    <div class="modal-footer">
				    	<div class="col s6 offset-s3 m4 offset-m1" align="center">

							<a href="#!" class="modal-close waves-effect waves-light btn-flat" style=" color: #ffffff; background-color: #d32f2f">Cancelar</a>
							
				    	</div>
				    	<div class="col s6 offset-s3 m4 offset-m2" align="center">
				    		<button id="btn_EntSal" class="btn waves-effect waves-light" type="submit" name="action">Enviar
							   <i class="material-icons right">send</i>
							</button>
				    		
				    	</div>
				    </div>
				  </div>

  		</div>
  		<?php
	      if (isset($form_error)) {
	        ?>
		        <span class="helper-text" style="color:red;">
		          <?php echo $form_error; ?>
		        </span>
	      <?php
	    	}
	      ?>

		<?php echo $this->tag->endForm(); ?>	    
		
      </div>
    </div>
</div>

<!-- Compiled and minified JavaScript -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
<script type="text/javascript">
  M.AutoInit();

  $(document).ready(function() {
    $('input#Matricula').characterCounter();
  });

	$(document).ready(function(){
	    $('.slider').slider();
  	});

  	$(document).ready(function(){
	    $('.tabs').tabs();
	  });
			


  	$(document).ready(function(){
		var scrollValue = 250;
		$('html, body').animate({scrollTop : scrollValue},700);
	});
</script>


<script type="text/javascript">

        $(document).ready(function(){
            $("#boton_ajax").click(function(){

            	var id_P = document.getElementById("Matricula").value;

                $.ajax({
                    url: "<?php echo $this->url->get("gestion/ajaxVotante")?>",
                    type:'GET',
                    dataType: 'json',
                    data: {id_person: id_P}

                }).done(function (data) {
                	
                	if(!(typeof data === 'string'))
                	{	
                		document.getElementById("label_header").innerHTML = "Resultado de Consulta";
		                document.getElementById('label_header').style.color = '#000000';
		                document.getElementById("row_header_user").style.display = "block";
                		document.getElementById("img_user_modal").style.display = 'block';
                		document.getElementById("Id_Dentro").value = data.Dentro;
                		document.getElementById("btn_EntSal").style.display = 'block';

                		if (data.Dentro == '0') {
                			document.getElementById("btn_EntSal").innerHTML = 'Registrar';
                			document.getElementById("btn_EntSal").style.backgroundColor = '#1976d2';
                		}
                		else{
                			document.getElementById("btn_EntSal").innerHTML = 'Volver a Registrar';
                			document.getElementById("btn_EntSal").style.backgroundColor = '#ffa000';
                		}

                		
	            		document.getElementById("label_header_user").innerHTML = "Información Estudiante";
	            		document.getElementById('label_header_user').style.color = '#000000';
	            		document.getElementById("label_mat").innerHTML = "Matrícula:";
						document.getElementById("label_nom").innerHTML = "Nombre:";
	            		document.getElementById("matricula_ajax").innerHTML = data.Id_Persona;
						document.getElementById("nombre_ajax").innerHTML = data.Nombre+" "+data.Ap_Paterno+" "+data.Ap_Materno;
                	}
                	else{
            		  document.getElementById("matricula_ajax").innerHTML = "";
					  document.getElementById("nombre_ajax").innerHTML = "";
					  document.getElementById("label_mat").innerHTML = "";
					  document.getElementById("label_nom").innerHTML = "";
					  document.getElementById("label_header").innerHTML = "ERROR EN CONSULTA";
					  document.getElementById('label_header').style.color = '#d32f2f';

					  document.getElementById("btn_EntSal").style.display = 'none';
					  document.getElementById("img_user_modal").style.display = 'none';
					  document.getElementById("row_header_user").style.display = "none";
                	}
                	
					});     
            });
        });

</script>
